//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_ReservaSalon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public  class Formulario
    {
        [Required]
        public int Id { get; set; }

        [Required]

        public string Cedula { get; set; }
        [Required]
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [Display(Name ="Salon")]
        public int IdSalon { get; set; }
        [Required]
        [Display(Name = "Numero de personas")]
        public int MaxPersonas { get; set; }

        [Required]
        
        [Display(Name = "Fecha de Reservacion")]
        [DataType(DataType.DateTime)]
        public DateTime FechaReserva { get; set; }

        [Required]
        [DataType(DataType.Time)]
        [Display(Name = "Hora de Reservacion")]
        public System.TimeSpan TiempoReserva { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Salon Salon { get; set; }
    }
}
