//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_ReservaSalon
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class Salon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salon()
        {
            this.Formulario = new HashSet<Formulario>();
        }
        [Required]
        public int Id { get; set; }
        [Required]
        [Display(Name ="Nombre de Salon")]
        public string Nombre { get; set; }
        [Required]
        [Display(Name ="Tipo de Salon")]
        public int IdTipoSalon { get; set; }
        [Required]
        public string Ubicacion { get; set; }
        public bool Disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formulario> Formulario { get; set; }
        public virtual TipoSalon TipoSalon { get; set; }
    }
}
