//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Salones
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Formulario
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Cedula { get; set; }

        [Required]
        public string Nombre { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string Telefono { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Tipo de Salon")]
        public int IdSalon { get; set; }

        [Required]
        [Display(Name = "Numero de Personas")]
        public int MaxPersonas { get; set; }
        [Required]
        public int IdNombreSalon { get; set; }
        public string NombreSalon { get; set; }

        [Required]
        [Display(Name = "Fecha de reservacion")]
        [DataType(DataType.Date)]
        public System.DateTime FechaReserva { get; set; }

        [Required]
        [Display(Name = "Hora de reservacion")]
        [DataType(DataType.Time)]
        public System.TimeSpan TiempoReserva { get; set; }

        [Display(Name = "Fecha de Creacion")]
        public Nullable<System.DateTime> FechaCreacion { get; set; }

        [Display(Name = "Tipo de Salon")]
        public virtual TipoSalon TipoSalon { get; set; }

    }
}
