//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva_Salones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon
    {
        public int Id { get; set; }
        public string Imagen { get; set; }
        public string Nombre { get; set; }
        public int IdTipoSalon { get; set; }
        public string Ubicacion { get; set; }
        public bool Disponible { get; set; }
    
        public virtual TipoSalon TipoSalon { get; set; }
    }
}
